-- ============================================================
-- MIGRATION 5 of 5: Seed churches — SDA West Conference
-- Paste this entire file into the Supabase SQL Editor and click Run.
-- Safe to re-run: clears existing church data first.
-- ============================================================

-- Remove any previously seeded churches before inserting
truncate table churches restart identity cascade;

insert into churches (name, country, region) values
  ('Adonai SDA Church',                                  'United States', 'Norwalk'),
  ('Alhambra SDA Church',                                'United States', 'Alhambra'),
  ('All Nations SDA Church',                             'United States', 'Monrovia'),
  ('Altadena SDA Church',                                'United States', 'Altadena'),
  ('Antelope Valley SDA Church',                         'United States', 'Lancaster'),
  ('Baldwin Park Bilingual SDA Church',                  'United States', 'Baldwin Park'),
  ('Bellflower-Lakewood SDA Church',                     'United States', 'Bellflower'),
  ('Berean SDA Church',                                  'United States', 'Los Angeles'),
  ('Bethel SDA Church',                                  'United States', 'Pomona'),
  ('Breath of Life SDA Church',                          'United States', 'Inglewood'),
  ('Burbank SDA Church',                                 'United States', 'Burbank'),
  ('Camarillo SDA Church',                               'United States', 'Camarillo'),
  ('Canoga Park Community SDA Church',                   'United States', 'Winnetka'),
  ('Carson Spanish SDA Church',                          'United States', 'Carson'),
  ('Central Filipino SDA Church',                        'United States', 'Los Angeles'),
  ('Central Japanese-American Comm. SDA Church',         'United States', 'Pasadena'),
  ('Central Spanish SDA Church',                         'United States', 'Los Angeles'),
  ('Cerritos Korean SDA Church',                         'United States', 'Norwalk'),
  ('Chino Valley Chinese SDA Church',                    'United States', 'Chino'),
  ('Community Adventist Fellowship',                     'United States', 'Sierra Madre'),
  ('Compton Community SDA Church',                       'United States', 'Compton'),
  ('Compton-Samoan SDA Church',                          'United States', 'Compton'),
  ('Crescenta Valley Filipino SDA Church',               'United States', 'Montrose'),
  ('Culver City SDA Church',                             'United States', 'Los Angeles'),
  ('Culver City Spanish SDA Church',                     'United States', 'Los Angeles'),
  ('Delaware Avenue SDA Church',                         'United States', 'Santa Monica'),
  ('Downey-Florence SDA Church',                         'United States', 'Downey'),
  ('Eagle Rock SDA Church',                              'United States', 'Los Angeles'),
  ('East Los Angeles Bilingual SDA Church',              'United States', 'Los Angeles'),
  ('EastMont Spanish SDA Church',                        'United States', 'Los Angeles'),
  ('Ebenezer Spanish SDA Church',                        'United States', 'Los Angeles'),
  ('El Camino A Cristo Spanish SDA Church',              'United States', 'Huntington Park'),
  ('El Monte SDA Church',                                'United States', 'El Monte'),
  ('El Monte Spanish SDA Church',                        'United States', 'El Monte'),
  ('El Monte Vietnamese SDA Church',                     'United States', 'El Monte'),
  ('El Rio Spanish SDA Church',                          'United States', 'Oxnard'),
  ('El Sereno Spanish SDA Church',                       'United States', 'Los Angeles'),
  ('El-Shaddai Spanish SDA Church',                      'United States', 'Los Angeles'),
  ('Emmanuel Seventh-day Adventist Church',              'United States', 'Los Angeles'),
  ('Ephesus SDA Church',                                 'United States', 'Los Angeles'),
  ('Fifty-Fourth Street SDA Church',                     'United States', 'Los Angeles'),
  ('Gardena Genesis Community SDA Church',               'United States', 'Gardena'),
  ('Gardena Japanese American SDA Church',               'United States', 'Gardena'),
  ('Gerizim Spanish SDA Church',                         'United States', 'Los Angeles'),
  ('German-American SDA Church',                         'United States', 'Torrance'),
  ('Glassell Park Spanish SDA Church',                   'United States', 'Los Angeles'),
  ('Glendale City SDA Church',                           'United States', 'Glendale'),
  ('Glendale Filipino SDA Church',                       'United States', 'Glendale'),
  ('Glendale Korean SDA Church',                         'United States', 'Los Angeles'),
  ('Glendale Spanish SDA Church',                        'United States', 'Glendale'),
  ('Glendale West Spanish SDA Church',                   'United States', 'Los Angeles'),
  ('Glendora Spanish SDA Church',                        'United States', 'Glendora'),
  ('Hacienda Heights SDA Church',                        'United States', 'Hacienda Heights'),
  ('Hawthorne SDA Church',                               'United States', 'Hawthorne'),
  ('Hollydale Community SDA Church',                     'United States', 'South Gate'),
  ('Hollywood SDA Church',                               'United States', 'Hollywood'),
  ('Hollywood Spanish SDA Church',                       'United States', 'Los Angeles'),
  ('Huntington Park Spanish Church',                     'United States', 'Huntington Park'),
  ('Indonesian-American SDA Church',                     'United States', 'Azusa'),
  ('Kaleo Seventh-day Adventist Church',                 'United States', 'Glendale'),
  ('La Puente Spanish SDA Church',                       'United States', 'City Of Industry'),
  ('La Voz Sylmar Spanish SDA Church',                   'United States', 'Sylmar'),
  ('Lancaster SDA Church',                               'United States', 'Lancaster'),
  ('Lancaster Spanish SDA Church',                       'United States', 'Quartz Hill'),
  ('Light Above SDA Church',                             'United States', 'Glendale'),
  ('Lincoln Heights Spanish SDA Church',                 'United States', 'Los Angeles'),
  ('Living Hope SDA Church',                             'United States', 'Los Angeles'),
  ('Living Stones SDA Church',                           'United States', 'La Crescenta'),
  ('Long Beach SDA Church',                              'United States', 'Long Beach'),
  ('Long Beach Spanish SDA Church',                      'United States', 'Long Beach'),
  ('Los Angeles Central Korean SDA Church',              'United States', 'Los Angeles'),
  ('Los Angeles Chinese SDA Church',                     'United States', 'Alhambra'),
  ('Los Angeles Eastside Korean SDA Church',             'United States', 'Hacienda Heights'),
  ('Los Angeles Tongan SDA Church',                      'United States', 'Bellflower'),
  ('Los Olivos Spanish SDA Church',                      'United States', 'Van Nuys'),
  ('Lynwood Spanish SDA Church',                         'United States', 'Lynwood'),
  ('Maranatha SDA Church',                               'United States', 'Inglewood'),
  ('Mid City Spanish SDA Church',                        'United States', 'Los Angeles'),
  ('Miramonte Boulevard SDA Church',                     'United States', 'Los Angeles'),
  ('Monrovia Spanish SDA Church',                        'United States', 'Monrovia'),
  ('Normandie Avenue SDA Church',                        'United States', 'Los Angeles'),
  ('North Hills SDA Church',                             'United States', 'Claremont'),
  ('Northridge SDA Church',                              'United States', 'Northridge'),
  ('Norwalk SDA Church',                                 'United States', 'Norwalk'),
  ('Ojai Valley SDA Church',                             'United States', 'Ojai'),
  ('Olympic Korean SDA Church',                          'United States', 'Los Angeles'),
  ('Oxnard All Nations SDA Church',                      'United States', 'Oxnard'),
  ('Palmdale SDA Church',                                'United States', 'Palmdale'),
  ('Panamericana Spanish SDA Church',                    'United States', 'Los Angeles'),
  ('Panorama Spanish SDA Church',                        'United States', 'Panorama City'),
  ('Paramount Spanish SDA Church',                       'United States', 'Bellflower'),
  ('Pasadena SDA Church',                                'United States', 'Pasadena'),
  ('Pasadena Spanish SDA Church',                        'United States', 'Pasadena'),
  ('Philadelphian SDA Church',                           'United States', 'Long Beach'),
  ('Pico Rivera Bilingual SDA Church',                   'United States', 'Pico Rivera'),
  ('Ridgecrest SDA Church',                              'United States', 'Ridgecrest'),
  ('Rolling Hills SDA Church',                           'United States', 'Rolling Hills Estates'),
  ('Rosemead Korean SDA Church',                         'United States', 'Rosemead'),
  ('Russian-American SDA Church',                        'United States', 'Glendale'),
  ('San Fernando Spanish SDA Church',                    'United States', 'Mission Hills'),
  ('San Gabriel Valley Spanish Church',                  'United States', 'El Monte'),
  ('Santa Barbara SDA Church',                           'United States', 'Santa Barbara'),
  ('Santa Clarita SDA Church',                           'United States', 'Santa Clarita'),
  ('Santa Monica SDA Church',                            'United States', 'Santa Monica'),
  ('Simi Valley SDA Church',                             'United States', 'Simi Valley'),
  ('Smyrna SDA Church',                                  'United States', 'Los Angeles'),
  ('South Bay SDA Church',                               'United States', 'Redondo Beach'),
  ('South Gate Spanish SDA Church',                      'United States', 'Lynwood'),
  ('Spanish-American SDA Church',                        'United States', 'Los Angeles'),
  ('Sunland-Tujunga SDA Church',                         'United States', 'Tujunga'),
  ('Sylmar SDA Church',                                  'United States', 'Sylmar'),
  ('Tamarind Avenue SDA Church',                         'United States', 'Compton'),
  ('Tehachapi SDA Church',                               'United States', 'Tehachapi'),
  ('Temple City SDA Church',                             'United States', 'Temple City'),
  ('Temple City Spanish SDA Church',                     'United States', 'San Gabriel'),
  ('The Place Adventist Fellowship Church',              'United States', 'Newbury Park'),
  ('Thousand Oaks SDA Church',                           'United States', 'Thousand Oaks'),
  ('University SDA Church',                              'United States', 'Los Angeles'),
  ('Vallejo Drive SDA Church',                           'United States', 'Glendale'),
  ('Valley Crossroads SDA Church',                       'United States', 'Pacoima'),
  ('Valley United Korean SDA Church',                    'United States', 'Granada Hills'),
  ('Van Nuys SDA Church',                                'United States', 'Van Nuys'),
  ('Van Nuys Spanish SDA Church',                        'United States', 'Van Nuys'),
  ('Ventura SDA Church',                                 'United States', 'Ventura'),
  ('West Covina Hills SDA Church',                       'United States', 'West Covina'),
  ('West Hollywood Spanish SDA Church',                  'United States', 'Los Angeles'),
  ('West Los Angeles Japanese SDA Church',               'United States', 'West Los Angeles'),
  ('White Memorial SDA Church',                          'United States', 'Los Angeles'),
  ('Whittier SDA Church',                                'United States', 'Whittier');
